### ISSUE TITLE
Create An Order

### ISSUE THREAD

**Issue by rahul-m-patel** [CSCI-GA-2820-FA23-001/orders#1]
**As a** customer
**I need** to be able to create an order
**So that** I can start shopping/ordering items  
   
 ### Details and Assumptions
 * This is essentially the customer's shopping cart, eventually containing all of the user's items they want to buy.
 * We will be storing the order details in a database
 * Each order will consist of item id, item name, quantity, price per item and the total order amount
 * Initially there are no orders in the database. When the user places the order, there should be 1 order in the database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the customer is ready to start buying items
 When they add the first item to the shopping cart
 Then their order should be created.
```

**Comment by JooooosephY** [comment]
It may be Create an Order rather than Create Orders. Because only one order can be created at one time.
