### ISSUE TITLE
Read An Item

### ISSUE THREAD

**Issue by VirajYParikh** [CSCI-GA-2820-FA23-001/orders#10]
**As a** customer
**I want** to list an item
**So that** I can see the details of an item.

### **Assumptions and Details**
* The API must list all the details of the item in depth. This should have all the details of the item in comparison to the "List All Items" API since the user wants to get a greater look into the item.

### **Acceptance Criteria**

 ```gherkin
When I select an item 
I should be able to see all the details of the item on the page.
 ```

**Comment by JooooosephY** [comment]
I think this one should be Read an Item. List should only list all the items in the order.
