### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by JooooosephY** [CSCI-GA-2820-FA23-001/orders#13]
**As a** developer
**I need** to create the database for the Orders microservice
**So that** I can store the data of Orders and Items permanently
   
 ### Details and Assumptions
 * We need to choose a relational database to store the data of Orders and Items. 
 * We need to build our database based on the designed database schema. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the database is created based on the design
 When the developer sends queries to the database
 Then the corresponding data can be queried, created, deleted, and updated properly. 
```

**Comment by VirajYParikh** [comment]
Reviewed by Viraj
