### ISSUE TITLE
Create Database Schema

### ISSUE THREAD

**Issue by JooooosephY** [CSCI-GA-2820-FA23-001/orders#14]
**As a** developer
**I need** to have the database schema to create the database
**So that** the database for our microservice can be properly built. 
   
 ### Details and Assumptions
 * The schema should be designed according to how the item and order are stored in the database. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a well-designed database schema
 When the developer builds the database based on the schema
 Then the data can be stored properly to fulfill the needs of the microservices 
```

**Comment by VirajYParikh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-fa23-001-650a5f7ceb520710c4ca00da/issues/CSCI-GA-2820-FA23-001/orders/14?planning-poker) with Zenhub @JooooosephY @Matt-J-Dong @rahul-m-patel

**Comment by VirajYParikh** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-fa23-001-650a5f7ceb520710c4ca00da/issues/CSCI-GA-2820-FA23-001/orders/14?planning-poker) with Zenhub @starz107

**Comment by JooooosephY** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-fa23-001-650a5f7ceb520710c4ca00da/issues/CSCI-GA-2820-FA23-001/orders/14?planning-poker) with Zenhub @VirajYParikh

**Comment by VirajYParikh** [comment]
Reviewed
