### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by JooooosephY** [CSCI-GA-2820-FA23-001/orders#2]
**As a** developer
**I need** a descriptive README
**So that** other developers can understand what is happening in the repository.
   
 ### Details and Assumptions
 * README should contain a quick description of the work and how to continue development.
   
 ### Acceptance Criteria  
   
 ```
 Given the README is in a completed/updated state
 When the developer reads the README
 Then the developer should understand how they can contribute.
```

**Comment by Matt-J-Dong** [comment]
Every time a developer makes an update, they should update the README with their own update because they are the one who understands it the best.
