### ISSUE TITLE
Create an Item

### ISSUE THREAD

**Issue by JooooosephY** [CSCI-GA-2820-FA23-001/orders#3]
**As a** customer
**I need** to add an item to an order
**So that** the order would have the items that the customer bought
   
 ### Details and Assumptions
 * One item should be created and associated with a given order. 
 * In the database, the item should have the Item ID, the quantity of this item, the unit price of this item, and the associated order ID. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the function to create an item
 When we call POST /orders/<order-id>/items/item-id
 Then after refreshing the page, I should see the new item just created in the provided order. 
```

**Comment by VirajYParikh** [comment]
Should incorporate overall integration of the portal with the database.
